### ISSUE TITLE
PulseAudio Noise Supression Plugin

### ISSUE THREAD

**Issue by LiamDawe** [josh-richardson/cadmus#2]
It's not actually made clear, do we need to have the PulseAudio Noise Supression Plugin already installed?

**Comment by josh-richardson** [comment]
No, everything is self-contained in the released binaries.

**Comment by LiamDawe** [comment]
I see, in that case, it appears to either not work or do nothing in my quick testing with the AppImage on Manjaro.

What's the best way to actually ensure it's running? As simply tapping my finger and recording shows a zero difference in Audacity.

**Comment by josh-richardson** [comment]
You want to be either using the pulseaudio `Default output`, or if you can see it in Audacity, `Denoised Microphone`. Cadmus creates a virtual output named `Denoised Microphone`, but not all apps are able to see it (many will limit you to physical devices). If you open `pavucontrol`, and take a look at the `Input Devices` tab, you ought to see `Denoised Microphone` (make sure you're showing all devices). The denoised microphone ought to only light up when you actually speak, rather than when you type. 

I do plan to add a troubleshooting section to the readme, and to add more detailed instructions.

**Comment by josh-richardson** [comment]
Having had a quick look at Audacity specifically, it seems that it doesn't respect the Pulseaudio default device, and nor does it allow you to select the denoised microphone in the settings dialog. However, if you start recording and then open `pavucontrol`, select the `Recording` tab, and then select `Denoised Microphone` as the source, it seems to work. This is a bit hacky - hopefully it can be addressed in future, although I'm not sure how.

If it looks something like this, it's working & you'll definitely hear the difference:
![image](https://user-images.githubusercontent.com/13924368/86026809-cf24ae80-ba27-11ea-86a1-a1a4652a4f2c.png)

**Comment by LiamDawe** [comment]
Ah ha! There we go, perhaps some of this can be noted in the docs? Seems it does work :)

**Comment by josh-richardson** [comment]
> Ah ha! There we go, perhaps some of this can be noted in the docs? Seems it does work :)

For sure, I'll add it to the readme for now, and write a dedicated troubleshooting section in the coming days. Do reopen this if you have any further issues.

**Comment by directentis1** [comment]
I also faced the same problem with Audacity and solved it the way you mentioned.
But I feel that the quality of my voice after denoising is greatly reduced, it sounds like a broken voice or a stuffy nose.
