### ISSUE TITLE
Too aggressive

### ISSUE THREAD

**Issue by VortexAcherontic** [josh-richardson/cadmus#8]
I just tested the 0.0.1 release (AppImage) and everything I hear are some crackle while with the app off everything is fine.

I appended the recording done with cadmus on:
[unbenannt.zip](https://github.com/josh-richardson/cadmus/files/4847217/unbenannt.zip)

**Comment by Half-Shot** [comment]
I'm also getting absolute silence with this enabled.

**Comment by josh-richardson** [comment]
This may be due to PulseAudio not being set up properly. On your 'Recording' tab in pavucontrol, you should see the `Loopback to LADSPA Plugin Noise Suprressor for Voice...` - the source should be set to the name of your recording device (in my case Logitech C920 in this screenshot):

![image](https://user-images.githubusercontent.com/13924368/86047924-985e9080-ba47-11ea-88e3-4085ba846142.png)

Then, in any application which is recording, the source in the recording tab should be set to 'Denoised Microphone', as indicated below:

![image](https://user-images.githubusercontent.com/13924368/86048051-c93ec580-ba47-11ea-94f1-8d75721a021a.png)

If this isn't the case, it may be that Cadmus is buggy or doesn't work with your system. If you're still getting no noise whatsoever then I'll need to look into this further.

**Comment by Half-Shot** [comment]
Turns out the"Loopback to" wasn't listening to anything according to the Recording tab of `pavucontrol`. I switched it to my mic and it worked. Possibly some problematic device selection logic, because I definitely selected the correct microphone from the menu.
Now it's working, it's very cool. Thank you :)

**Comment by Half-Shot** [comment]
Oh, looks like #9 describes my issue.

**Comment by josh-richardson** [comment]
I agree, I think it refers to the same problem. I'm going to close this & merge discussion to #9
