### ISSUE TITLE
Incorrect source in loopback

### ISSUE THREAD

**Issue by C-512L** [josh-richardson/cadmus#9]
I just installed cadmus to try but it didnt work but after a little try and error found the problem
after i switched the source of "Loopback to LADSPA Plugin Noise Suppressor for Voice (Mono) on Null Output" from "Denoised Microphone" to "Built-in Audio Analog Stereo" (the microphone source) It worked without major issues.
![Screenshot_2020-06-29_21-25-27](https://user-images.githubusercontent.com/29307937/86047351-107c8480-ba4f-11ea-8fdd-7cef5f482235.png)

**Comment by josh-richardson** [comment]
This is a known bug, I think due to Cadmus not setting the default recording device back to the previously selected one on exit.

**Comment by josh-richardson** [comment]
Pasted from a closed issue for any other people finding this:

This may be due to Cadmus not setting PulseAudio up properly. On your 'Recording' tab in pavucontrol, you should see the `Loopback to LADSPA Plugin Noise Suprressor for Voice...` - the source should be set to the name of your recording device (in my case Logitech C920 in this screenshot):

![image](https://user-images.githubusercontent.com/13924368/86047924-985e9080-ba47-11ea-88e3-4085ba846142.png)

Then, in any application which is recording, the source in the recording tab should be set to 'Denoised Microphone', as indicated below:

![image](https://user-images.githubusercontent.com/13924368/86048051-c93ec580-ba47-11ea-94f1-8d75721a021a.png)

If this isn't the case, it may be that Cadmus is buggy or doesn't work with your system. If you're still getting no noise whatsoever then I'll need to look into this further.

**Comment by C-512L** [comment]
ok i think i have found something
it works as expected when any app is using a microphone (Edit: it also fails sometimes)
when i first tried and failed i had discord connected to a voice chat. i also found that it doesn t always happen.
so my guess is that cadmus is buggy recognizing or asignating the input sources

**Comment by Half-Shot** [comment]
@josh-richardson today after clicking "Enable Noise Suppression", I found it had tried to denoise the "Denoised Microphone". It was connected to itself :/

**Comment by josh-richardson** [comment]
This has been addressed in #26 and as such I'm closing this issue. Please do re-open it if the new version doesn't fully solve this issue.
